/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Product_qtys_Manager.java
 *
 * Created on May 27, 2014, 3:36:00 PM
 */
package Reports;

import classgroup.JComboHandle;
import classgroup.JavaValidation;
import classgroup.ReportGenerator;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author javalok
 */
public class Report_Creditor extends javax.swing.JInternalFrame {

    private JavaValidation javaValidation;
    private Connection conn;
    private PreparedStatement pstm = null;
    private ResultSet rs = null;
    private String q = "";

    /** Creates new form Product_qtys_Manager */
    public Report_Creditor(java.sql.Connection conn) {
        initComponents();
        this.conn = conn;
        javaValidation = new JavaValidation();

        jTextFieldStartDate.setEnabled(false);
        jTextFieldStartDate.setVisible(false);
        jLabel3.setVisible(false);
        jTextFieldEndDate.setEnabled(false);
        jTextFieldEndDate.setVisible(false);
        jLabel4.setVisible(false);
        jPanel1.updateUI();
        jPanel1.revalidate();

        fillCreditorNameCombo();

    }

      public void fillCreditorNameCombo() {
        try {
            q = "select name from tbl_creditor_list";
            new JComboHandle(conn).fillComboCreditorName(jComboBoxCreditorName, q);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void ReportGenerateAction() {
        if (jComboBoxCreditorName.getSelectedItem().toString().equalsIgnoreCase("import report")) {
            if (jRadioButtonDaily.isSelected() == true) {
                q = "select * from tbl_import_product_record where date = '" + jTextFieldStartDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/IncomeReport.jrxml",conn);
            }
            if (jRadioButtonMonthly.isSelected() == true) {
                q = "select * from tbl_import_product_record where date between '" + jTextFieldStartDate.getText() + "' and '" + jTextFieldEndDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/IncomeReport.jrxml",conn);
            }
        } else if (jComboBoxCreditorName.getSelectedItem().toString().equalsIgnoreCase("selling report")) {
            if (jRadioButtonDaily.isSelected() == true) {
                q = "select * from tbl_selling_product_record where date = '" + jTextFieldStartDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/SellReport.jrxml",conn);
            }
            if (jRadioButtonMonthly.isSelected() == true) {
                q = "select * from tbl_selling_product_record where date between '" + jTextFieldStartDate.getText() + "' and '" + jTextFieldEndDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/SellReport.jrxml",conn);
            }
        } else if (jComboBoxCreditorName.getSelectedItem().toString().equalsIgnoreCase("damaged report")) {
            if (jRadioButtonDaily.isSelected() == true) {
                q = "select * from tbl_damage_lost_record where date = '" + jTextFieldStartDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/DamagedReport.jrxml",conn);
            }
            if (jRadioButtonMonthly.isSelected() == true) {
                q = "select * from tbl_damage_lost_record where date between '" + jTextFieldStartDate.getText() + "' and '" + jTextFieldEndDate.getText() + "'";
                new ReportGenerator().GenerateReport(q, "Reports/DamagedReport.jrxml",conn);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldStartDate = new javax.swing.JTextField();
        jComboBoxCreditorName = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldEndDate = new javax.swing.JTextField();
        jRadioButtonDaily = new javax.swing.JRadioButton();
        jRadioButtonMonthly = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancel = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();

        setClosable(true);
        setTitle("Creditors Reports");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(-16777216,true)));

        jLabel1.setText("Creditor Name");

        jLabel2.setText("Start Date");

        jTextFieldStartDate.setToolTipText("");
        jTextFieldStartDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldStartDateMouseClicked(evt);
            }
        });
        jTextFieldStartDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStartDateActionPerformed(evt);
            }
        });
        jTextFieldStartDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldStartDateKeyTyped(evt);
            }
        });

        jComboBoxCreditorName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        jLabel3.setText("Report Type");

        jLabel4.setText("End Date");

        jTextFieldEndDate.setToolTipText("");
        jTextFieldEndDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldEndDateMouseClicked(evt);
            }
        });
        jTextFieldEndDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEndDateActionPerformed(evt);
            }
        });
        jTextFieldEndDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextFieldEndDateKeyTyped(evt);
            }
        });

        buttonGroup1.add(jRadioButtonDaily);
        jRadioButtonDaily.setText("Daily");
        jRadioButtonDaily.setOpaque(false);
        jRadioButtonDaily.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRadioButtonDailyItemStateChanged(evt);
            }
        });
        jRadioButtonDaily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonDailyActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonMonthly);
        jRadioButtonMonthly.setText("Monthly");
        jRadioButtonMonthly.setOpaque(false);
        jRadioButtonMonthly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMonthlyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(39, 39, 39)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonDaily)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonMonthly)
                        .addGap(9, 9, 9))
                    .addComponent(jComboBoxCreditorName, 0, 173, Short.MAX_VALUE)
                    .addComponent(jTextFieldStartDate)
                    .addComponent(jTextFieldEndDate))
                .addGap(49, 49, 49))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCreditorName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRadioButtonDaily)
                    .addComponent(jRadioButtonMonthly))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextFieldEndDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButtonCancel.setText("Cance");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Generate");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonAdd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCancel)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldStartDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldStartDateMouseClicked
        new NepaliCalendarClassGroup.NepaliDate().setTextFieldWithNepaliDateValue(jTextFieldStartDate);
        jButtonCancel.setEnabled(true);
}//GEN-LAST:event_jTextFieldStartDateMouseClicked

    private void jTextFieldStartDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStartDateActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTextFieldStartDateActionPerformed

    private void jTextFieldStartDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldStartDateKeyTyped
          javaValidation.getDateValue(evt);
}//GEN-LAST:event_jTextFieldStartDateKeyTyped

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        JOptionPane.showMessageDialog(this, "Data Should Store/Transact More Than a Month");
        //this.ReportGenerateAction();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextFieldEndDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldEndDateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEndDateMouseClicked

    private void jTextFieldEndDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEndDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEndDateActionPerformed

    private void jTextFieldEndDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEndDateKeyTyped
         javaValidation.getDateValue(evt);
    }//GEN-LAST:event_jTextFieldEndDateKeyTyped

    private void jRadioButtonDailyItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRadioButtonDailyItemStateChanged
}//GEN-LAST:event_jRadioButtonDailyItemStateChanged

    private void jRadioButtonDailyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonDailyActionPerformed
        jTextFieldStartDate.setEnabled(true);
        jTextFieldStartDate.setVisible(true);
        jLabel3.setVisible(true);
        jTextFieldEndDate.setEnabled(false);
        jTextFieldEndDate.setVisible(false);
        jLabel4.setVisible(false);
        jPanel1.updateUI();
        jPanel1.revalidate();
}//GEN-LAST:event_jRadioButtonDailyActionPerformed

    private void jRadioButtonMonthlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMonthlyActionPerformed
        jTextFieldStartDate.setEnabled(true);
        jTextFieldStartDate.setVisible(true);
        jLabel3.setVisible(true);
        jTextFieldEndDate.setEnabled(true);
        jTextFieldEndDate.setVisible(true);
        jLabel4.setVisible(true);
        jPanel1.updateUI();
        jPanel1.revalidate();
}//GEN-LAST:event_jRadioButtonMonthlyActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox jComboBoxCreditorName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButtonDaily;
    private javax.swing.JRadioButton jRadioButtonMonthly;
    private javax.swing.JTextField jTextFieldEndDate;
    private javax.swing.JTextField jTextFieldStartDate;
    // End of variables declaration//GEN-END:variables
}
